version: '3'
services:
        nginx:
                build:
                        dockerfile: ./Dockerfile
                        context: .
                image: bastosv/web-brumadinho
                container_name: web-brumadinho
                ports:
                        - "8000:80"
                volumes:
                        - ..://usr/local/share/html/
                command:
                        - /usr/bin/nginx -g daemon off;